const express = require('express');
const router = express.Router();
const { getDb } = require('../database');
const { ObjectId } = require('mongodb');
const campaignEditService = require('../services/campaignEditService');
const stripeService = require('../services/stripeService');
const { notifyAdvertiser, resolveAdDisplayName } = require('../services/advertiserEmailService');

/** Verify the authenticated user owns the campaign. */
async function verifyCampaignOwnership(req, res) {
  const db = getDb();
  let id;
  try { id = new ObjectId(req.params.id); } catch (_) {
    res.status(400).json({ error: 'Invalid campaign ID' });
    return null;
  }
  const campaign = await db.collection('adCampaigns').findOne({ _id: id });
  if (!campaign) { res.status(404).json({ error: 'Campaign not found' }); return null; }
  const advertiser = await db.collection('advertisers').findOne({ _id: campaign.advertiserId });
  if (!advertiser || advertiser.userId !== req.user.uid) {
    res.status(403).json({ error: 'Forbidden' }); return null;
  }
  return campaign;
}

async function queueCampaignReview(db, campaign, reqUserId, description) {
  const now = new Date();
  if (['scheduled', 'pending_review'].includes(campaign.status)) {
    await db.collection('adCampaigns').updateOne(
      { _id: campaign._id },
      { $set: { status: 'pending_review', updatedAt: now } }
    );
  }
  await db.collection('adSubmissions').updateOne(
    { _id: campaign.submissionId },
    {
      $set: {
        status: 'manual_review',
        updatedAt: now,
        reviewRequestedByUserAt: now,
      },
    }
  );
  await db.collection('reviewFlags').insertOne({
    submissionId: campaign.submissionId,
    flagType: 'user_requested_changes',
    description,
    severity: 'medium',
    autoGenerated: false,
    resolvedAt: null,
    resolvedBy: null,
    createdAt: now,
    createdBy: reqUserId || null,
  });
}

// PUT /:id/creative — edit creative content
router.put('/:id/creative', async (req, res) => {
  try {
    const db = getDb();
    const campaign = await verifyCampaignOwnership(req, res);
    if (!campaign) return;
    const result = await campaignEditService.updateCreative(campaign._id, req.body);
    if (!result.success) return res.status(400).json({ error: result.error });
    if (result.reviewRequired) {
      const description = campaign.status === 'active'
        ? 'User changed a live campaign. Keep the current ad running and review the update before it replaces the approved version.'
        : 'User changed campaign details before launch. Review is required before the ad can run.';
      await queueCampaignReview(db, campaign, req.user?.uid, description);
    }
    res.json({
      message: result.reviewRequired && campaign.status === 'active'
        ? 'success_pending_review'
        : 'success',
    });
  } catch (err) { res.status(500).json({ error: err.message }); }
});

// PUT /:id/event — edit event fields
router.put('/:id/event', async (req, res) => {
  try {
    const db = getDb();
    const campaign = await verifyCampaignOwnership(req, res);
    if (!campaign) return;
    const result = await campaignEditService.updateEventFields(campaign._id, req.body);
    if (!result.success) return res.status(400).json({ error: result.error });
    if (result.reviewRequired) {
      const description = campaign.status === 'active'
        ? 'User changed details on a live event campaign. Keep the approved event ad live until the updated version is reviewed.'
        : 'User changed event details before launch. Review is required before the ad can run.';
      await queueCampaignReview(db, campaign, req.user?.uid, description);
    }
    res.json({
      message: result.reviewRequired && campaign.status === 'active'
        ? 'success_pending_review'
        : 'success',
    });
  } catch (err) { res.status(500).json({ error: err.message }); }
});

// POST /:id/cancel — advertiser ends campaign early (no refunds for captured charges; see product policy)
router.post('/:id/cancel', async (req, res) => {
  try {
    const db = getDb();
    const campaign = await verifyCampaignOwnership(req, res);
    if (!campaign) return;

    if (!['active', 'scheduled', 'pending_review'].includes(campaign.status)) {
      return res.status(400).json({ error: 'Campaign cannot be cancelled in its current status' });
    }

    const submission = await db.collection('adSubmissions').findOne({ _id: campaign.submissionId });

    // Release an uncaptured card authorization only (not a refund)
    if (submission?.paymentMode === 'manual_capture' && submission.paymentIntentId) {
      try {
        await stripeService.releaseAuthorization(submission.paymentIntentId, 'Advertiser cancelled before capture');
      } catch (err) {
        console.warn('[campaignManagement] Authorization release failed:', err.message);
      }
    }

    const refundAmountInCents = 0;

    const now = new Date();
    // Cancel the campaign
    await db.collection('adCampaigns').updateOne(
      { _id: campaign._id },
      { $set: { status: 'cancelled', cancelledAt: now, updatedAt: now } }
    );

    // Update submission
    await db.collection('adSubmissions').updateOne(
      { _id: campaign.submissionId },
      { $set: { status: 'cancelled', updatedAt: now } }
    );

    // Remove adTargeting records
    await db.collection('adTargeting').deleteMany({ campaignId: campaign._id });

    const adDisplayName = await resolveAdDisplayName(db, campaign.creativeId);
    notifyAdvertiser(campaign.advertiserId, 'campaign_cancelled', { refundAmount: refundAmountInCents, adDisplayName });

    res.json({ message: 'success', data: { cancelled: true, refundAmountInCents } });
  } catch (err) { res.status(500).json({ error: err.message }); }
});

// GET /:id/refund-estimate — advertiser self-cancellation does not refund (kept for client compatibility)
router.get('/:id/refund-estimate', async (req, res) => {
  try {
    const db = getDb();
    const campaign = await verifyCampaignOwnership(req, res);
    if (!campaign) return;

    res.json({
      message: 'success',
      data: {
        refundAmountInCents: 0,
        remainingDays: 0,
        totalDays: 0,
      },
    });
  } catch (err) { res.status(500).json({ error: err.message }); }
});

module.exports = router;
